#!/bin/sh

# Reindents the MATLAB source code file given in argument.

if [ -z "$1" ]; then
    echo "Give a filename in argument"
    exit 1
fi

SCRIPTS_DIR=$(pwd)/$(dirname $0)

cd $(dirname $1)
emacs -batch $(basename $1) -l ${SCRIPTS_DIR}/indent-matlab.el
